### ISSUE TITLE
Dolphin Texture UV Difference

### ISSUE THREAD

**Issue by Offroaders123** [ozelot379/ConvertJavaTextureToBedrock#10]
**Describe the issue**
- When converting to the Bedrock resource pack format, I noticed that the Dolphin texture only moves the texture to the correct directory, but it does not change the texture to align with the Bedrock version of the Dolphin texture UV. This doesn't appear to be an issue with your program, just a missed detail between the two versions' formatting.

Is there an error message?
- There is no error message, everything finishes/converts successfully.

Which step is previous the error message?
- There is no error message, everything finishes/converts successfully.

Is it the same error/step or is different if you try multiple times?
- I imagine this would occur every time because this issue doesn't appear to be something going wrong with your program, just a missed detail in the conversion process.

**Images**
Texture UV Comparison:
![Dolphin UV](https://user-images.githubusercontent.com/65947371/84730587-662f3800-af4b-11ea-8596-389253754f95.png)

Result of UV Differences in Gameplay:
![image](https://user-images.githubusercontent.com/65947371/84728684-a344fb80-af46-11ea-9775-a7ec2f6bb8e8.png)

**Texture pack**
Link to the resource pack: [Faithful 1.16 (Snapshot 9)](https://faithful.team/faithful-1-16-snapshot-9/)

**System info**
Windows 10 on iMac using Bootcamp

**Converting**
System OS: Windows 10
Browser: Google Chrome

**Game**
System OS: Minecraft for Windows 10

**Comment by ozelot379** [comment]
@Offroaders123

Yes, you're right, I forgot the conversion of the dolphin texture

I added it now in v3.5.0

Work that for you too?

**Comment by Offroaders123** [comment]
@ozelot379 

Awesome, thanks for the fix! It works perfectly as of v3.5.1 as well :)
