### ISSUE TITLE
Convert entity

### ISSUE THREAD

**Issue by shihadaman** [ozelot379/ConvertJavaTextureToBedrock#11]
**Describe the issue**
Please consult the readme before you report an issue 

A clear and concise description of what the issue is.
 It doesnt convert the new textures like piglin and hoglin and zoglin also it dont put new nether meterials in the right folder and doesnt convert the particles of soul fire and it doesnt rename soul fire weapons and finally it dont put the font in the right folder .

Is there an error message? No

Which step is previous the error message?

Is it the same error/step or is different if you try multiple times?

**System info**

***Converting***
System OS: 
Browser: 

***Game***
System OS: android

**Texture pack**
(optimal, but on advantage, so that issues can be analyzed and fixed more precisely)
Link to download:

**Comment by ozelot379** [comment]
@shihadaman v1.16 is currently not fully supported - I'm working on it

**Comment by ozelot379** [comment]
@shihadaman
The textures you mentioned (and some others) of v1.16 are now supported on v3.6.0 of the converter

Fonts are not supported (yet)

Works that for you?
