### ISSUE TITLE
Pack world creation crash

### ISSUE THREAD

**Issue by DogeIsCut** [ozelot379/ConvertJavaTextureToBedrock#12]
**Describe the issue**
Bedrock Editon crashes when loading a world or creating a new world when using this pack

other textures work fine however.

**System info**

***Converting***
System OS: Windows 10
Browser: Google Chrome

***Game***
Windows 10 edition

**Texture pack**
cant :( just know its vanilla tweaks
https://vanillatweaks.net/share#eaCalw

**Comment by ozelot379** [comment]
@DogeIsCut
VanillaTweak is using an array in `description` which Bedrock not supports, so Bedrock will mark the texture pack as invalid
This is now supported in https://github.com/ozelot379/ConvertJavaTextureToBedrock/issues/24
Is this may fixing also your crash problem?
If not, I think it's an bug of Bedrock self, not of the converter
