### ISSUE TITLE
Converted Chromahills all banners not displaying correctly

### ISSUE THREAD

**Issue by jasherr** [ozelot379/ConvertJavaTextureToBedrock#14]
**Describe the issue**
Please consult the readme before you report an issue

A clear and concise description of what the issue is.
Converted Chromahills resource pack and all seems to be working very nicely except for banners which only show up as white (screenshot attached) this happens with both experimental and normal convert

Is there an error message?
No converts just fine

Which step is previous the error message?

Is it the same error/step or is different if you try multiple times?

Are the textures available/correct on Java version?
Yes
**System info**

***Converting***
System OS:  Windows 10
Browser:  Chrome 83.0.4103.116 

***Game***
System OS:  Windows 10

**Texture pack**
(optimal, but on advantage, so that issues can be analyzed and fixed more precisely)
Link to download:  https://www.chromahills.com/
![Screenshot (3)](https://user-images.githubusercontent.com/60027019/86578367-0dd5de00-bfbf-11ea-90ad-8b00d40c5d04.png)

**Comment by ozelot379** [comment]
@jasherr
I improved in v4.0.2 the the following points in relation with banners:

- Fix banner pattern black
- Fix banner pattern preview max size
- Fix banner illager pattern

Does that solve your problem?

**Comment by ozelot379** [comment]
@jasherr 

I close this because no feedback and I think it should solved the problem
