### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Cheftehini** [ozelot379/ConvertJavaTextureToBedrock#15]
**Describe the issue**
to begin i know nothing about coding i would just like to help with data

A clear and concise description of what the issue is.
im able to open the mcpack into bedrock edition and select it the problem occurs during world generation 
there is no error message it just crashes the game ive tried both experimental and none 
it just crashes the games
Is it the same error/step or is different if you try multiple times?
ive tried multiple times and creating/join a world crashes the game
Are the textures available/correct on Java version?
yes
**System info**
core i7 10750H
GTX 1660 TI
***Converting***
System OS: windows 10
Browser: 

***Game***
System OS: windows 10

**Texture pack**
Classic alternative
Link to download: https://www.planetminecraft.com/texture-pack/classic-alternative/

**Comment by ozelot379** [comment]
I think this is the same problem like in https://github.com/ozelot379/ConvertJavaTextureToBedrock/issues/7

**Comment by Cheftehini** [comment]
then it should work right didnt you fix it?

**Comment by Cheftehini** [comment]
Hello?

**Comment by ozelot379** [comment]
@Cheftehini
This not really a problem with this converter tool

It works with Bedrock iOS and Bedrock Launcher (Android / Linux)

I think it's a bug in Bedrock Windows 10 self

May you can get more crash infos if you look in the Windows Event Viewer
