### ISSUE TITLE
Mythic Resource Pack

### ISSUE THREAD

**Issue by ospai** [ozelot379/ConvertJavaTextureToBedrock#16]
Piglin's don't texture correctly only the piglin brute properly converted I'm sure it was definitely caused from the update as they added the piglin brute 
![Minecraft 8_12_2020 1_41_00 PM](https://user-images.githubusercontent.com/69598460/90048424-81939680-dca1-11ea-926d-b6cc2f9b6927.png)

**Comment by ospai** [comment]
Also paintings show up as invisible not all but the large ones

**Comment by ozelot379** [comment]
@ospai
I removed the piglin converter in v4.0.2 that needed for Bedrock v1.16.0 and now identical to Java version since Bedrock version v1.16.20

Does that solve your first problem?

Are the paintings still incorrect?

**Comment by ospai** [comment]
They're still showing up as invisible but the piglin problem is fixed

**Comment by ospai** [comment]
Just noticed some more paintings are showing up the ones that cover two blocks and the single block ones but the huge ones and some others that cover two blocks as well aren't showing up

**Comment by ozelot379** [comment]
@ospai 
The painting and particle textures are incomplete in the 'Mythic Resource Pack', so they are transparent in the converted sprite image

They already some warn logs since v4.0.2, in v4.0.3 I styled it now yellow for better make visible it

**Comment by ospai** [comment]
thanks! I wasn't sure if it was the pack or the converter
