### ISSUE TITLE
Leather Armor texture using .tga doesn't work.

### ISSUE THREAD

**Issue by HaragOnMC** [ozelot379/ConvertJavaTextureToBedrock#17]
**Describe the issue**
Leather Armor texture using .tga doesn't work. To fix this bug, you need to put the oppacity of the texture to 1 to 2.

Is there an error message?
No.
Which step is previous the error message?
No.
Is it the same error/step or is different if you try multiple times?
No.
Are the textures available/correct on Java version?
Yes.
**System info**

***Converting***
System OS: Windows 10
Browser: 

***Game***
System OS: 

**Texture pack**
(optimal, but on advantage, so that issues can be analyzed and fixed more precisely)
Link to download: https://faithful.team/faithful-64x/

**Comment by ozelot379** [comment]
@HaragOnMC 
What is not working for you?

![image](https://user-images.githubusercontent.com/16632028/93709354-fded8500-fb3d-11ea-8e61-3d6979483296.png)

![image](https://user-images.githubusercontent.com/16632028/93709393-2a090600-fb3e-11ea-8d32-d976c835fa62.png)

![image](https://user-images.githubusercontent.com/16632028/93709306-a8b17380-fb3d-11ea-83bc-b26fd3c74fce.png)

**Comment by HaragOnMC** [comment]
Hello! Here is my problem when trying to convert my pack to Bedrock.
![Capture](https://user-images.githubusercontent.com/57374230/93711664-5594ec00-fb50-11ea-95d0-16976e347176.PNG)

**Comment by ozelot379** [comment]
@HaragOnMC
OK, I could now follow up

Thanks for hint to set the alpha to `2` for `OverlayToTranslateConverter`

Works it now for you in v4.0.5?

**Comment by HaragOnMC** [comment]
Hello!
It works fine, thanks :)
