### ISSUE TITLE
When i tried to convert the purebdcraft 512x texture pack, this error appeared

### ISSUE THREAD

**Issue by avijitb129** [ozelot379/ConvertJavaTextureToBedrock#18]
![Screenshot_20200916-102400](https://user-images.githubusercontent.com/62600282/93292331-27897200-f807-11ea-813a-61d62235d7fa.png)
**Describe the issue**
Please consult the readme before you report an issue

A clear and concise description of what the issue is.

Is there an error message?

Which step is previous the error message?

Is it the same error/step or is different if you try multiple times?

Are the textures available/correct on Java version?

**System info**

***Converting***
System OS: 
Browser: 

***Game***
System OS: 

**Texture pack**
(optimal, but on advantage, so that issues can be analyzed and fixed more precisely)
Link to download:

**Comment by ozelot379** [comment]
@avijitb129
I think it's the same issue like in https://github.com/ozelot379/ConvertJavaTextureToBedrock/issues/13#issuecomment-655620566
