### ISSUE TITLE
XP Bar is a bit broken.

### ISSUE THREAD

**Issue by HaragOnMC** [ozelot379/ConvertJavaTextureToBedrock#19]
**Describe the issue**
Please consult the readme before you report an issue

The beginning and the ending of the XP bar is broken with black pixel. And the green part (when you get xp) is still like Bedrock one not like my texture on Java.
![Capture](https://user-images.githubusercontent.com/57374230/93718546-745da780-fb7d-11ea-9023-e5cb25fef7da.PNG)

Same texture pack as I have send to you from my first bug report.

**Comment by ozelot379** [comment]
https://github.com/ozelot379/ConvertJavaTextureToBedrock/issues/17

**Comment by HaragOnMC** [comment]
I have a fix for this:
http://www.mediafire.com/folder/7vrp6a9vjvj3k

**Comment by ozelot379** [comment]
Works for me
![image](https://user-images.githubusercontent.com/16632028/93898105-25398300-fcf3-11ea-835f-c962cc56722c.png)

@HaragOnMC
- Have you enabled experimental features or not?
- Did you restart Minecratf Bedrock after you select the texture pack?

**Comment by HaragOnMC** [comment]
Yes of course!

**Comment by HaragOnMC** [comment]
I did everything.

**Comment by HaragOnMC** [comment]
But don't worry, I managed to fix the issue.

**Comment by ozelot379** [comment]
ok
