### ISSUE TITLE
Black Squares on Texture Hardtop Vanillaccurate 128x

### ISSUE THREAD

**Issue by Shinzef** [ozelot379/ConvertJavaTextureToBedrock#20]
**Describe the issue**
Black Squares on Texture Hardtop Vanillaccurate 512x

A clear and concise description of what the issue is.
there are black squares on the texture of stone and sandstone 
in java it didnt exist 
![image](https://user-images.githubusercontent.com/72062931/94516404-4dc3fe80-0258-11eb-8fb7-8622d1be073b.png)

Is there an error message?
no

Which step is previous the error message?

Is it the same error/step or is different if you try multiple times?

Are the textures available/correct on Java version?
yes

**System info**
I5 9300H
gtx 1650
12gb ram

***Converting***
System OS: Windows 10
Browser: Chrome

***Game***
System OS: Windows 10

**Texture pack**
(optimal, but on advantage, so that issues can be analyzed and fixed more precisely)
Link to download: https://www.curseforge.com/minecraft/texture-packs/hardtop-vanillaccurate-pack/download/3040389

**Comment by Shinzef** [comment]
![image](https://user-images.githubusercontent.com/72062931/94516686-ee1a2300-0258-11eb-9cb2-d1e62c7601d7.png)
here is a clearer picture

**Comment by ozelot379** [comment]
Same with grass block top texture too

![image](https://user-images.githubusercontent.com/16632028/94573676-9b4d6500-0272-11eb-8c23-3cb8164a4d31.png)

**Comment by Shinzef** [comment]
Whats the fix for it

**Comment by ozelot379** [comment]
Seems Minecraft Bedrock doesn't like grayscale typed images, like the author of this texture pack is using

At first glance, the following textures are affected, among others:

- `textures/block/anvil_base.png`
- `textures/block/anvil_top_damaged_0.png`
- `textures/block/anvil_top_damaged_1.png`
- `textures/block/anvil_top_damaged_2.png`
- `textures/block/bedrock.png`
- `textures/block/glass_black.png`
- `textures/block/glass_gray.png`
- `textures/block/glass_silver.png`
- `textures/block/glass_white.png`
- `textures/block/glass_pane_top_black.png`
- `textures/block/glass_pane_top_gray.png`
- `textures/block/glass_pane_top_silver.png`
- `textures/block/glass_pane_top_white.png`
- `textures/block/grass_top.png`
- `textures/block/observer_top.png`
- `textures/block/stone.png`
- `textures/block/stone_slab_side.png`
- `textures/block/stone_slab_top.png`
- `textures/block/vine.png`

Sandstone seems to work (It's already a color typed image)

@Shinzef You should be able to fix by convert it to color typed images

For instance in `GIMP`, you can select it on `Image > Mode > RGB`, but I think, other image programs can this too, if you use an other (Except maybe `MS Paint` ...)

Or just remove those images, if you can't convert and if it understandably unplayable for you

**Comment by ozelot379** [comment]
![image](https://user-images.githubusercontent.com/16632028/94999627-eccf5a00-05ba-11eb-99da-8a8ac11e83a9.png)

**Comment by ozelot379** [comment]
@Shinzef
Help this for you?

**Comment by Shinzef** [comment]
Thanks for the fix still havent tried will comment again if the fixed work
