### ISSUE TITLE
Chest texture wrong

### ISSUE THREAD

**Issue by Unagami13** [ozelot379/ConvertJavaTextureToBedrock#21]
**Describe the issue**
Please consult the readme before you report an issue

A clear and concise description of what the issue is.
The chest,traped chest and the ender chest have a wrong texture inside is outside and outside is inside
Is there an error message?
no
Which step is previous the error message?
nothing
Is it the same error/step or is different if you try multiple times?
Yes
Are the textures available/correct on Java version?
I am pretty sure.
**System info**
?
***Converting***
System OS: 
Browser: 

***Game***
System OS: 

**Texture pack**
(optimal, but on advantage, so that issues can be analyzed and fixed more precisely)
Link to download:

**Comment by ozelot379** [comment]
@Unagami13 
Which texture pack you had converted?

**Comment by Unagami13** [comment]
Dandelion

**Comment by ozelot379** [comment]
The chest texture are wrong even in Minecraft Java

The change for chest textures was for Minecraft Java 1.15

Seems the texture pack wasn't updated for Minecraft Java 1.15 or 1.16 correctly

This converter only supports convert the old Java chest textures, if the texture pack is based for Minecraft Java 1.13 or 1.14

![screenshot](https://user-images.githubusercontent.com/16632028/96144040-039f7600-0f04-11eb-8c6f-bc0d4e28a2ec.png)

**Comment by Unagami13** [comment]
Thanks for helping me out :) I will find a 1.16 texture my self.  Gesendet von Mail für Windows 10 Von: ozelot379Gesendet: Donnerstag, 15. Oktober 2020 16:44An: ozelot379/ConvertJavaTextureToBedrockCc: Unagami13; CommentBetreff: Re: [ozelot379/ConvertJavaTextureToBedrock] Chest texture wrong (#21) The chest texture are wrong even in Minecraft JavaThe change for chest textures was for Minecraft Java 1.15Seems the texture pack wasn't updated for Minecraft Java 1.15 or 1.16 correctlyThis converter only supports convert the old Java chest textures, if the texture pack is based for Minecraft Java 1.13 or 1.14—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe. 



	
		
			
				
			
		
		
			
				Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
				www.avast.com
