### ISSUE TITLE
Json descriptions not being handled

### ISSUE THREAD

**Issue by rtm516** [ozelot379/ConvertJavaTextureToBedrock#24]
Is there an error message?
The game fails to load the resource pack due to its description being JSON, I have handled this in my Java port of this library for Geyser in this commit https://github.com/GeyserMC/PackConverter/commit/cb8d8ebc7d5688d542fbb8378d7a32c111e78dcc 

Which step is previous the error message?
N/A

Is it the same error/step or is different if you try multiple times?
No

Are the textures available/correct on Java version?
Yes

**System info**

***Converting***
System OS: Win 10 1909
Browser: Chrome 86

***Game***
System OS: Win10 1.16.40

**Texture pack**
Link to download: https://vanillatweaks.net/share#sfp7WO

**Comment by KimJongUninstall** [comment]
I'm getting the same issue with vanilla tweaks packs. based on the error, its something with the way vanilla tweaks does its description, and it not working with bedrock descriptions. probably the colored text and what not. not sure though...

**Comment by KimJongUninstall** [comment]
I have successfully imported vanilla tweaks after changing the manifest.json file to match the same syntax as another bedrock resource pack. the importer does a poor job at converting the java syntax over the the much simpler bedrock syntax, and it breaks some things. This is how the manifest.json file should look:
![image](https://user-images.githubusercontent.com/39226074/98504470-0c464c00-2225-11eb-9e23-acb9e16ce188.png)

Much nicer than what the importer creates:
![image](https://user-images.githubusercontent.com/39226074/98504542-3bf55400-2225-11eb-8f68-9b78dafae83d.png)
It seems the converter doesn't really know what to do with the pack.mcmeta info, and just throws it all in the wrong places, while also missing necessary syntax such as the min_version_engine line. If you just match what I made for my changes, it should import correctly.

**Comment by ozelot379** [comment]
@rtm516
I found no such library you using in GeyserMC/PackConverter, but I hope the convert of `description` should now work, if it's an array, in v4.1.0

@KimJongUninstall
The converter generates now `format_version` `2` of `manifest.json` in v4.1.0
But it should not be the problem, the `format_version` `1` still works, the problem is, that Bedrock not supports `description` array like Java does, this is will be converted now to a string in v4.1.0
