### ISSUE TITLE
Doesn't convert languages?

### ISSUE THREAD

**Issue by vinivosh** [ozelot379/ConvertJavaTextureToBedrock#27]
**Describe the issue**
This might be asking too much, but I presumed this would also convert other resources added by the resource pack, not only textures. I tested a resource pack that adds a new language to minecraft, but it doesn't seem to convert it.

**System info**

***Converting***
System OS: Windows 10 Pro
Browser: 

***Game***
System OS: Windows 10 Pro

**Texture pack**
Link to download: https://wiki.lojban.io/Jbogugde_Minecraft_Server

**Comment by ozelot379** [comment]
@vinivosh 
I don't think this is possible

Even if the Java format (.json) could be converted to Bedrock format (.lang), the language keys are too much different and not for compare with textures
