### ISSUE TITLE
Stuck on the option to start conversion

### ISSUE THREAD

**Issue by yugi1408** [ozelot379/ConvertJavaTextureToBedrock#3]
Okay so when I try and convert a pack it comes up saying start conversion but the green button (which I assume you press to start conversion) has 3 dots as if its loading and it was like this for at least half an hour.

**Comment by ozelot379** [comment]
With which browser you are trying?

After you select/drag a pack, the conversion starts automatic and the 3 animated dots means the conversion is in progress.

But of course it isn't thought that it stucks on the first step 'Start conversion' (over half an hour).

I think your browser does not supports some syntax (therefore there is no feedback), other errors would be shown in the gui.

**Comment by ozelot379** [comment]
I have improved the error handling in v3.0.0, can you now see a error message? When yes, which?

**Comment by ozelot379** [comment]
@yugi1408 some feedback?

**Comment by yugi1408** [comment]
sorry I wasn't on for a while

**Comment by ozelot379** [comment]
@yugi1408 

ok, but works it now for you?

if not with which browser you are trying?

**Comment by ozelot379** [comment]
@yugi1408 

I close this because no feedback

If you still have problems reopen it or create a new
