### ISSUE TITLE
ERROR: Expected '(' every time.

### ISSUE THREAD

**Issue by Galileo88** [ozelot379/ConvertJavaTextureToBedrock#5]
I have used this tool a lot in the past, but now, Im  getting the error every single time I use it, regardless of which pack I try. Am I doing something wrong? I have tried the zip and the extracted version of all packs.

**System info**
System OS: Windows 10
Browser: Edge

**Comment by ozelot379** [comment]
@Galileo88 
Which type of Edge are you using?
Edge on Chromium based or on EdgeHTML based?

**Comment by Galileo88** [comment]
It was Edge HTML based. I tried with Chrome and was able to convert the packs. Thanks! I'll close this issue now.
