### ISSUE TITLE
Classic Alternative causing crashes on world loading

### ISSUE THREAD

**Issue by StoneBricks53** [ozelot379/ConvertJavaTextureToBedrock#7]
**Describe the issue**
The resource packs convert just fine, and when they are loaded in, the main menu music used with the resource pack plays, as well as the main menu screen and Minecraft logo are also changed to those in the resource pack. However, when I load a world with one of these packs, the game loads for a couple of seconds before crashing without an error message. 
Also, I am not sure if the game running the beta (1.16 snapshot) would be a cause of an issue since other 1.14 packs work just fine with it. 

**System info**
System OS: Windows 10
Browser: Firefox and Opera

**Texture pack**
The texture packs tried are Classic Alternative and Classic Alternative Neon.
Link to download: https://www.planetminecraft.com/texture_pack/classic-alternative/

**Comment by ozelot379** [comment]
Works on Bedrock v1.14

**Comment by ozelot379** [comment]
@StoneBricks53 
Please note snapshots versions are not supported and if it crashed, it doesn't necessarily have to do with the texture pack and this converter can't do much (even stable versions)

**Comment by ozelot379** [comment]
@StoneBricks53
The new v1.16 textures are now supported on v3.6.0 of the converter

I have no crashes

Work it now for you?

**Comment by Cheftehini** [comment]
its not working though you said you fixed it

**Comment by ozelot379** [comment]
@Cheftehini
I didn't write I fixed something.
I did nothing because while this issue was inital created, v1.16 was a unsupported snapshot version and after release of v1.16, I support the new texures, I asked if it still crash.

**Comment by ozelot379** [comment]
@StoneBricks53 
This not really a problem with this converter tool

It works with Bedrock iOS and Bedrock Launcher (Android / Linux)

I think it's a bug in Bedrock Windows 10 self

May you can get more crash infos if you look in the Windows Event Viewer?

**Comment by Gaminbrew** [comment]
@ozelot379 Faulting application name: Minecraft.Windows.exe, version: 1.16.20.3, time stamp: 0x5f236b9c
Faulting module name: d3d11.dll, version: 10.0.18362.387, time stamp: 0x7e72d1cb
Exception code: 0xc0000005
Fault offset: 0x000000000011f4f0
Faulting process id: 0xa34
Faulting application start time: 0x01d67ce5d25c8e0a
Faulting application path: C:\Program Files\WindowsApps\Microsoft.MinecraftUWP_1.16.2003.0_x64__8wekyb3d8bbwe\Minecraft.Windows.exe
Faulting module path: C:\Windows\SYSTEM32\d3d11.dll
Report Id: 766be2f8-fa18-4883-9694-3c3d2558ab7e
