### ISSUE TITLE
Icon becomes blank when it is held in the hand

### ISSUE THREAD

**Issue by mjdwyc** [ozelot379/ConvertJavaTextureToBedrock#8]
**Describe the issue**
Selected icon shows blank when there is something in the quick bar (not sure what it's called)
Is there an error message? No

So basically my hand is holding the starter map at slot 1, but it shows empty on my screen. I can see the map on my hand. If I have multiple items, the one that gets selected becomes empty.

**System info**
System OS: Windows 10
Browser: Firefox 75.0

**Texture pack**
~Dandelion~ (Biomes o Plenty support) for version 1.15
Link to download: https://www.dropbox.com/s/54ry0qglgmnaj7x/TPs.zip?dl=1
Where the link is found: https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/resource-packs/1243109-16x-1-8-dandelion-biomes-o-plenty-support-updated?page=32
![Annotation 2020-05-03 161618](https://user-images.githubusercontent.com/11084577/80909265-65817000-8d16-11ea-9302-23c6d20bdde8.png)

**Comment by ozelot379** [comment]
In the Java version the selected hotbar slot seems to be behind the item, in the Bedrock version before it

I think in the most texture packs the area on item is transparent, but in the texture pack you use it's not tranpsarent

I improved it to remove the part on the item area in v3.3.3

@mjdwyc Is that help you? The texture pack differs so from Java to Bedrock, but at least the selected item is now visible

**Comment by mjdwyc** [comment]
I think it broke something, because the tree leaves are now not transparent 
![Annotation 2020-05-03 205344](https://user-images.githubusercontent.com/11084577/80914747-21ee2c80-8d3d-11ea-907d-fc475793154e.png)

but yes, the item shows up now on the item slot!

**Comment by mjdwyc** [comment]
Some windows also became jumbled up, like this one. It was fine before.

![Annotation 2020-05-03 205548](https://user-images.githubusercontent.com/11084577/80914784-77c2d480-8d3d-11ea-935c-bdd58e87e003.png)

**Comment by ozelot379** [comment]
@mjdwyc 
Did you enable the experimental features?
Without it the ui textures should not be converted (it's very hard and buggy)
If you use the experimental features already before, did you restart Minecraft after selected the texture pack, like noted in the last step?
There seems cache bugs in the Bedrock version you can remove if you restart it

The black leaves comes if you disable the video settings "Fancy Graphics"
Have you enabled this setting?
But may it can be it's also a cache bug you can fix on restart

**Comment by mjdwyc** [comment]
Yes, I did turn on experimental to use v3.3.3 and I did restart Minecraft after the import is complete.

Ah, I might have the Fancy Graphics turned on.

**Comment by ozelot379** [comment]
I tested it now in the Bedrock versions in Windows 10, iOS and Android and it works like before

UI:
![IMG_1](https://user-images.githubusercontent.com/16632028/80916904-d5feb000-8d5b-11ea-9949-4f73e13654bb.PNG)

Leaves:
![IMG_2](https://user-images.githubusercontent.com/16632028/80916908-d8610a00-8d5b-11ea-8c09-2ff931eb56d8.PNG)

**Comment by mjdwyc** [comment]
Thanks so much for the help!
