### ISSUE TITLE
Command Line Interface

### ISSUE THREAD

**Issue by UndarkAido** [ozelot379/ConvertJavaTextureToBedrock#9]
I'm looking to try setting up a GitHub action to generate an MCPACK and I was wondering if there was any kind of command line interface if I installed this via the NPM repo. I can't seem to find any documentation.

**Texture pack**
Link to download: https://github.com/CyanideX/Unity https://github.com/UndarkAido/Unity/tree/1.14-actions

**Comment by ozelot379** [comment]
@UndarkAido 
I recently split this repo
I hadn't done this for the CLI part

I restored now the CLI part
Now you can find it at:
https://github.com/ozelot379/ConvertJavaTextureToBedrockCli
and in a separate NPM package https://www.npmjs.com/package/@ozelot379/convert-minecraft-java-texture-to-bedrock-cli

Works that for your purpose?

**Comment by UndarkAido** [comment]
Should work just fine, thank you so much!
